name: Bug report
description: Report an Issue to help and contribute to improve Project Patu
body:
  - type: markdown
    attributes:
      value: |
        Thanks for sparing the time to report the issue.
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: Tell us what happened.
      placeholder: A clear and concise description of what the issue is.
    validations:
      required: true
  - type: textarea
    id: to-reproduce
    attributes:
      label: How to Reproduce
      description: Help me reproduce the issue.
      placeholder: Steps to reproduce the Issue
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: what were you expecting.
      placeholder: A clear and concise description of what were you expecting to happen.
    validations:
      required: false
  - type: textarea
    id: deployment-environment
    attributes:
      label: Deployment Environment
      description: Please complete the following information
      placeholder: |
        Operating System: 
        Kernel Version: 
        Go Version:
    validations:
      required: true
  - type: textarea
    id: add-context
    attributes:
      label: Additional Context
      description: Include the output of `uname -a`, `cat /etc/os-release`, and Istio or linkerd version.
      placeholder: |
        Add any other context about the issue here, like
        *.* Patu container log files
        *.* Output of following commands `bpftool prog show / bpftool map show / bpftool btf show / bpftool cgroup tree`
    validations:
      required: false
