CC=clang
CFLAGS=-O2 -g  -Wall -target bpf -I/usr/include/$(shell uname -m)-linux-gnu

MACROS:=
DEBUG ?=

ifeq ($(DEBUG),1)
    MACROS:= $(MACROS) -DDEBUG
endif

TARGETS=patu_skmsg.o patu_skskb.o patu_sockops.o

%.o: %.c
	$(CC) $(CFLAGS) $(MACROS) -c $< -o $@

compile: $(TARGETS)

lint:
	clang-format --Werror -n ./*.c ./include/helpers/*.h

clean-obj:
	[ -f patu_skmsg.c ] && sudo rm -f $(TARGETS)
