name: C Code Checks

on:
  pull_request:
    branches:
      - main

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.after }}
  cancel-in-progress: true

jobs:
  c-code-checks:
    name: C Code Checks
    runs-on: ubuntu-22.04
    steps:
      - name: Install clang-format
        run: sudo apt-get update && sudo apt-get install -y clang-format
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run C Linter
        run: make -C bpf lint
      - name: Compile eBPF programs
        run: make -C bpf compile

 