name: e2e tests
on:
  pull_request:
    branches:
      - main

env:
  GO_VERSION: "1.18.4"

jobs:
  setup:
    name: setup
    runs-on: ubuntu-latest
    steps:
    - name: setup Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ env.GO_VERSION }}
      id: go

    - name: Install dependencies
      run: |
        go version
        go install golang.org/x/lint/golint@master

  e2e:
    name: e2e
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 100
    strategy:
      fail-fast: false
      matrix:
        ipFamily: ["ipv4"]
        backend: ["kubeproxy"]
    env:
      JOB_NAME: "patu-e2e-${{ matrix.ipFamily }}-${{ matrix.backend }}"
      IP_FAMILY: ${{ matrix.ipFamily }}
      BACKEND: ${{ matrix.backend }}
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Setup ebpf dependencies
      run: |
        export GOBIN=$(go env GOPATH)/bin
        export PATH=$PATH:$GOBIN
        echo "PATH=$PATH" >> $GITHUB_ENV
        go install github.com/cilium/ebpf/cmd/bpf2go@master
        sudo apt-get install -y clang llvm libelf-dev libpcap-dev gcc-multilib build-essential linux-tools-common

    - name: Setup cluster
      run: make -C test IP_FAMILY=${{ matrix.ipFamily }} BACKEND=${{ matrix.backend }} install-kind

    - name: Run e2e tests
      run: |
        export "PATH=$HOME/work/patu/patu/test/temp/e2e/bin:$PATH"
        make -C test IP_FAMILY=${{ matrix.ipFamily }} BACKEND=${{ matrix.backend }} KUBECONFIG=$HOME/.kube/config run-e2e

    - name: Export logs
      if: always()
      run: |
        ./test/scripts/e2e-export-logs.sh

    - name: Upload Junit Reports
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: kind-junit-${{ env.JOB_NAME }}-${{ github.run_id }}
        path: './test/scripts/temp/e2e/artifacts/reports/*.xml'

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v2
      if: always()
      with:
        report_paths: './test/scripts/temp/e2e/artifacts/reports/*.xml'
