name: Go Code Checks

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.after }}
  cancel-in-progress: true

jobs:
  go-code-lint:
    name: Go Code Linter
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Lint Go Code
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.46.2
          skip-cache: true
  
