name: Patu Performance Triggerable Workflow

on:
  issue_comment:
    types: [created, edited]


jobs:
  job-notification:
    name: set-pending-job-notifiation
    if: |
      contains(github.event.comment.body, '/run_bbq') &&
      ( github.event.comment.author_association == 'OWNER' ||
      github.event.comment.author_association == 'MEMBER' ||
      github.event.comment.author_association != 'CONTRIBUTOR' )
    runs-on: ubuntu-latest
    steps:
    - name: Add comment to the triggering issue number
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Performance tests have been requested :fire: [Requested Performance Test ${{ github.run_id }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) :fire:',
          });

  build-image:
    name: Build Patu Image
    needs: [ job-notification ]
    if: success()
    runs-on: ubuntu-latest
    env:
      REGISTRY: quay.io
      REPOSITORY: networksatatic
      IMAGE_NAME: patu
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

      - name: Login into Quay registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.QUAY_ROBOT_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_PASSWORD }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}
          tags: |
              # set latest tag for default branch
              type=raw,value=latest

      - name: Build and Push image to Quay
        id: build-and-push
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          context: .
          push: true
          file: deploy/Dockerfile
          build-args: kernel=5.15
          tags: quay.io/networkstatic/patu:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-perf-scale:
    name: deploy-perf-scale
    needs: [ build-image ]
    if: success()
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        cni: ["patu", "flannel"]
        kube-distribution: ["kubeadm"]
    env:
      JOB_NAME: "patu-triggered-perfscale-${{ matrix.k8s-distro }}-${{ matrix.cni }}"
      MATRIX_CNI: ${{ matrix.cni }}
      KUBE_DIST: ${{ matrix.k8s-distro }}
      AWS_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ANSIBLE_VAULT_PASSWORD_FILE: "/home/runner/work/patu/patu/vault-secret.txt"
      ANSIBLE_PRIVATE_KEY_FILE: "/home/runner/work/patu/patu/test/ansible/periodic/patu-ci.pem"
      ANSIBLE_REMOTE_USER: ${{ secrets.ANSIBLE_USER }}
      ANSIBLE_HOST_KEY_CHECKING: "False"

    steps:
    - name: Checkout Triggered PR
      uses: actions/checkout@v2
    - name: Checkout Pull Request
      run: hub pr checkout ${{ github.event.issue.number }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Ansible and dependencies
      run: pip3.10 install boto boto3 ansible-vault ansible-core==2.13.3

    - name: Install amazon.aws Ansible library
      run: ansible-galaxy collection install amazon.aws

    - name: Create ansible ssh key and vault passwd file
      run: |
        echo "${{ secrets.ANSIBLE_SSH_KEY }}" > /home/runner/work/patu/patu/test/ansible/periodic/patu-ci.pem
        chmod 0400 /home/runner/work/patu/patu/test/ansible/periodic/patu-ci.pem
        echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > /home/runner/work/patu/patu/vault-secret.txt
        chmod 0400 /home/runner/work/patu/patu/vault-secret.txt

    - name: Deploy EC2 Playbooks
      run: |
        ansible-playbook -vv ./test/ansible/periodic/deploy.yml --extra-vars "MATRIX_CNI=${{ matrix.cni }}" -i /home/runner/work/patu/patu/test/ansible/periodic/inventory.txt --private-key /home/runner/work/patu/patu/test/ansible/periodic/patu-ci.pem

    - name: Display Iperf3 Results for ${{ matrix.cni }}
      run: cat ./test/ansible/periodic/iperf-results-${{ matrix.cni }}.txt

# Temp disable for debugging nodes
#  clean:
#    name: terminate-tagged-ec2-instances
#    runs-on: ubuntu-latest
#    if: success() || failure()
#    needs: [ deploy-perf-scale ]
#    timeout-minutes: 10
#    env:
#      AWS_REGION: "us-east-1"
#      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#      ANSIBLE_VAULT_PASSWORD_FILE: "/home/runner/work/patu/patu/vault-secret.txt"
#      ANSIBLE_PRIVATE_KEY_FILE: "/home/runner/work/patu/patu/test/ansible/periodic/patu-ci.pem"
#      ANSIBLE_REMOTE_USER: ${{ secrets.ANSIBLE_USER }}
#      ANSIBLE_HOST_KEY_CHECKING: "False"
#    steps:
#    - name: checkout
#      uses: actions/checkout@v2
#
#    - uses: actions/setup-python@v4
#      with:
#        python-version: '3.10'
#
#    - name: Install Ansible and dependencies
#      run: pip3.10 install boto boto3 ansible-vault ansible-core==2.13.3
#
#    - name: Install amazon.aws Ansible library
#      run: ansible-galaxy collection install amazon.aws
#
#    - name: Create ansible ssh key and vault passwd file
#      run: |
#        echo "${{ secrets.ANSIBLE_SSH_KEY }}" > /home/runner/work/patu/patu/test/ansible/periodic/patu-ci.pem
#        chmod 0400 /home/runner/work/patu/patu/test/ansible/periodic/patu-ci.pem
#        echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > /home/runner/work/patu/patu/vault-secret.txt
#        chmod 0400 /home/runner/work/patu/patu/vault-secret.txt
#
#    - name: Deploy the EC2 Terminate Playbook
#      run: |
#        ansible-playbook -vv ./test/ansible/periodic/terminate-instances.yml
